org: adityakrshnn
app: redditspeedbot-serverless
service: redditspeedbot-serverless

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 600
  environment:
    NODE_ENV: dev

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  process:
    handler: app/handler.process
    layers:
      - ${param:FFMPEG_LAMBDA_LAYER}
    events:
      - http:
          path: process
          method: post
    environment:
      GFYCAT_CLIENT_ID: ${param:GFYCAT_CLIENT_ID}
      GFYCAT_CLIENT_SECRET: ${param:GFYCAT_CLIENT_SECRET}
      IMGUR_CLIENT_ID: ${param:IMGUR_CLIENT_ID}
      REDDIT_USERNAME: ${param:REDDIT_USERNAME}
      REDDIT_PASSWORD: ${param:REDDIT_PASSWORD}
      REDDIT_KEY: ${param:REDDIT_KEY}
      REDDIT_SECRET: ${param:REDDIT_SECRET}
      CATBOX_USERHASH: ${param:CATBOX_USERHASH}
      SENTRY_DSN: ${param:SENTRY_DSN}
      BLOCKED_SUBREDDITS: ${param:BLOCKED_SUBREDDITS}
      IMGUR_ALBUM_DELETE_HASH: ${param:IMGUR_ALBUM_DELETE_HASH}
